dist: trusty
env: "GRADLE_OPTS=\"-Xms1g -Xmx3g\""
branches:
  only:
  - master
jdk: 
  - oraclejdk8
before_install:
 - export MC_VERSION=$(grep -o 'version = '.*'' build.gradle | sed "s/'//g" | sed 's/version = //g' | sed $'s/\r$//')
 - export TRAVIS_TAG=${TRAVIS_TAG:-${MC_VERSION}.$(date +'%Y%m%d%H%M%S')}
 - chmod +x ./gradlew
 - echo $TRAVIS_TAG 
language: java
notifications: 
  email: true
script: 
  - export TOMLVERSIONLINE=$(sed -n '/zzversionline/=' /home/travis/build/mixxit/solinia3-ui/src/main/resources/META-INF/mods.toml)
  - export TOMLMINVERSIONLINE=$(sed -n '/zzminversionline/=' /home/travis/build/mixxit/solinia3-ui/src/main/resources/META-INF/mods.toml)
  - export TOMLVERSIONTOREPLACE=$(sed -n ${TOMLVERSIONLINE}p /home/travis/build/mixxit/solinia3-ui/src/main/resources/META-INF/mods.toml)
  - export TOMLMINVERSIONTOREPLACE=$(sed -n ${TOMLMINVERSIONLINE}p /home/travis/build/mixxit/solinia3-ui/src/main/resources/META-INF/mods.toml)
  - export TOMLMINVERSIONTOREPLACE=$(<<<"$TOMLMINVERSIONTOREPLACE" sed 's/[]"*[]/\\&/g')
  - export TOMLVERSIONTOSET="version=\"${TRAVIS_TAG}\" #mandatory zzversionline"
  - export TOMLMINVERSIONTOSET="    versionRange=\"[${MC_VERSION}]\" # zzminversionline"
  - sed -i -e "s/${TOMLVERSIONTOREPLACE}/${TOMLVERSIONTOSET}/" /home/travis/build/mixxit/solinia3-ui/src/main/resources/META-INF/mods.toml
  - sed -i -e "s/${TOMLMINVERSIONTOREPLACE}/${TOMLMINVERSIONTOSET}/" /home/travis/build/mixxit/solinia3-ui/src/main/resources/META-INF/mods.toml
  - sed -i -e "s/CIREPLACEMEVERSION/${TRAVIS_TAG}/g" /home/travis/build/mixxit/solinia3-ui/versions.json
  - sed -i -e "s/CIREPLACEMEMCVERSIONRANGE/${MC_VERSION}/g" /home/travis/build/mixxit/solinia3-ui/versions.json
  - "./gradlew build"
sudo: required
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: /home/travis/build/mixxit/solinia3-ui/build/libs/*.jar
    overwrite: true
    file_glob: true
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    deployment_file: /home/travis/build/mixxit/solinia3-ui/versions.json
    on:
      branch: master
after_deploy:
  - chmod +x senddiscord.sh
  - if [[ ! -e discordsent.tmp ]]; then
  - touch discordsent.tmp
  - ./senddiscord.sh $BOT_TOKEN $CHANNEL "A new version of Solinia3-UI [${TRAVIS_TAG}] has been released at https://github.com/mixxit/solinia3-ui/releases/download/${TRAVIS_TAG}/solinia3ui-${MC_VERSION}.jar"
  - fi
