dist: trusty
env: "GRADLE_OPTS=\"-Xms1g -Xmx3g\""
jdk: 
  - oraclejdk8
before_install:
 - chmod +x ./gradlew
language: java
notifications: 
  email: true
script: 
  - "./gradlew build"
sudo: required
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: solinia3-ui-builds
  local_dir: /home/travis/build/mixxit/solinia3-ui/build/libs
  verbose: true
  on:
    branch: master

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: /home/travis/build/mixxit/solinia3-ui/build/libs/*.jar
  overwrite: true
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
#after_success:
#  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
#  - chmod +x send.sh
#  - ./send.sh success $WEBHOOK_URL
#after_failure:
#  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
#  - chmod +x send.sh
#  - ./send.sh failure $WEBHOOK_URL
