import org.junit.Test;

import com.solinia.solinia3ui.ItemStackUtils;

import junit.framework.Assert;
import net.minecraft.item.ItemStack;

public class ItemStackUtilsTests {
	@Test
	public void DeserializeItemStackFromBase64() {
		String expectedName = "Fire Earrings of the Spirits";
		String sampleItem = "e2lkOiJtaW5lY3JhZnQ6c2tlbGV0b25fc2t1bGwiLENvdW50OjFiLHRhZzp7UHVibGljQnVra2l0VmFsdWVzOnsic29saW5pYTNjb3JlOnNvbGluaWFpZCI6MTE0MzE5LCJzb2xpbmlhM2NvcmU6c29sbGFzdHVwZGF0ZWQiOjE1NDY4OTU5NTAwMDBMLCJzb2xpbmlhM2NvcmU6bWVyY2hhbnQiOiJmYWxzZSJ9LFVuYnJlYWthYmxlOjFiLFNrdWxsT3duZXI6e0lkOiI1YTRmNWY3Yi1kNmNkLWNmOWQtN2QyZS0wNjcwYTAxNTY1NDciLFByb3BlcnRpZXM6e3RleHR1cmVzOlt7VmFsdWU6ImV5SjBaWGgwZFhKbGN5STZleUpUUzBsT0lqcDdJblZ5YkNJNkltaDBkSEE2THk5MFpYaDBkWEpsY3k1dGFXNWxZM0poWm5RdWJtVjBMM1JsZUhSMWNtVXZNbUZpWVRjMFpEZ3hNbVl6WXpWbE9UZGhaREJtTVdVMlkySXhaREkwWm1NNVpURXpOemc0TVRrMlkyWXhZbU0wTnpNeU1URm1aakUwTW1KbFlXSWlmWDE5In1dfX0sZGlzcGxheTp7TG9yZTpbJ3sidGV4dCI6Ikl0ZW1UeXBlOiDCp2FOT05FwqdyIn0nLCd7InRleHQiOiLCp2IvRVFVSVAgOiBFQVJTwqdyIn0nLCd7InRleHQiOiJDbGFzc2VzOiDCp2VNQUdJQ0lBTsKnciAifScsJ3sidGV4dCI6Ik1pbmltdW0gTGV2ZWw6IMKnZTI0wqdyIn0nLCd7InRleHQiOiJTVFI6IMKnYTbCp3IgQUdJOiDCp2E2wqdyICJ9JywneyJ0ZXh0IjoiREVYOiDCp2E2wqdyIElOVDogwqdhNsKnciAifScsJ3sidGV4dCI6IkNSOiDCp2I1wqdyICJ9JywneyJ0ZXh0IjoiwqdmSFA6IMKnZTYwwqdyIMKnZk1hbmE6IMKnZTUwwqdyIn0nLCd7InRleHQiOiJEaXNjb3ZlcmVkIEJ5OiBXdGoifScsJ3sidGV4dCI6IldvcnRoOiAxNzUifSddLE5hbWU6J3sidGV4dCI6IkZpcmUgRWFycmluZ3Mgb2YgdGhlIFNwaXJpdHMifSd9LERhbWFnZTozfX0=";		
		
		ItemStack itemStack = ItemStackUtils.convertBase64JsonToItemStack(sampleItem);
		
        Assert.assertEquals(expectedName, itemStack.getDisplayName().getString());
    }
	
}
